//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.50319.52000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("OpenKNX")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("3.3.1.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("3.3.1")]
[assembly: System.Reflection.AssemblyProductAttribute("OpenKNXproducer")]
[assembly: System.Reflection.AssemblyTitleAttribute("OpenKNXproducer")]
[assembly: System.Reflection.AssemblyVersionAttribute("3.3.1.0")]
