name: Check Build

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code OpenKNX.Toolbox.Sign
      uses: actions/checkout@v4
      with:
        repository: OpenKNX/OpenKNX.Toolbox.Sign
        ref: main
        path: OpenKNX.Toolbox.Sign

    - name: Checkout code OpenKNXproducer
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref || github.ref_name }}
        path: OpenKNXproducer

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0'

    - name: Run build script
      run: dotnet build OpenKNXproducer/OpenKNXproducer.csproj